# Import

In [2]:
import numpy as np

1. Сгенерировать матрицу размером 4 × 9, заполненную случайными целыми числами из отрезка [0,20] и вывести ее на на экран.

In [3]:
matrix = np.random.randint(1, 20, (4, 9))

2. Вывести на экран элемент с индексами [2, 6].

In [4]:
element_2_6 = matrix[2, 6]

element_2_6

np.int64(8)

3. Столбец под номером 3

In [5]:
column_3 = matrix[:, 2]

column_3

array([ 2, 19,  5, 12])

4. Каждый второй элемент третьей строки

In [6]:
every_second_element_row_3 = matrix[2, ::2]

every_second_element_row_3

array([13,  5,  6,  8,  8])

5. Элементы последнего столбца в обратном порядке

In [7]:
last_column_reversed = matrix[::-1, -1]

last_column_reversed

array([ 4,  8,  5, 16])

6. Изменение формы матрицы с 4x9 на 6x6 (будет ошибка, так как для изменения формы должно быть 36 элементов)

In [8]:
reshaped_matrix = np.resize(matrix, (6, 6))

reshaped_matrix

array([[ 2,  6,  2,  1,  4,  9],
       [19,  1, 16,  1, 19, 19],
       [13, 10, 19, 19,  5,  5],
       [13, 16,  5, 19,  6,  9],
       [ 8, 19,  8, 17,  1, 12],
       [14, 13, 10, 18, 18,  4]])

7. Возведение каждого элемента матрицы в степень 2

In [9]:
squared_matrix = np.power(matrix, 2)

squared_matrix

array([[  4,  36,   4,   1,  16,  81, 361,   1, 256],
       [  1, 361, 361, 169, 100, 361, 361,  25,  25],
       [169, 256,  25, 361,  36,  81,  64, 361,  64],
       [289,   1, 144, 196, 169, 100, 324, 324,  16]])

8. Минимум на главной диагонали

In [10]:
min_main_diagonal = np.min(np.diag(matrix))

min_main_diagonal

np.int64(2)

9. Максимальный элемент в предпоследнем столбце

In [11]:
max_in_penultimate_column = np.max(matrix[:, -2])

max_in_penultimate_column

np.int64(19)

10. Проверка, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность

In [12]:
flattened = matrix.flatten()
is_nonincreasing = np.all(np.diff(flattened) <= 0)

max_in_penultimate_column

np.int64(19)

11. Произведение ненулевых элементов на побочной диагонали

In [13]:
secondary_diagonal = np.diag(np.fliplr(matrix))
product_nonzero_secondary_diagonal = np.prod(secondary_diagonal[secondary_diagonal != 0])

product_nonzero_secondary_diagonal

np.int64(6400)

12. Массив из случайных целых чисел из [-20, 20] размерностью 15

In [14]:
random_array = np.random.randint(-20, 21, 15)

random_array

array([ 17,  15, -17,  11,  17,  20,  10,  19,   7,  -2, -19,  20,  18,
        10,  17])

13. Положительные элементы массива

In [15]:
positive_elements = random_array[random_array > 0]

positive_elements

array([17, 15, 11, 17, 20, 10, 19,  7, 20, 18, 10, 17])

14. Количество четных элементов в массиве

In [16]:
even_elements_count = np.sum(random_array % 2 == 0)

even_elements_count

np.int64(6)