# Import

In [47]:
import numpy as np

1. Сгенерировать матрицу размером 4 × 9, заполненную случайными целыми числами из отрезка [0,20] и вывести ее на на экран.

In [48]:
matrix = np.random.randint(1, 20, (4, 9))

matrix

array([[ 3, 19,  3, 18,  9, 19, 18,  1,  7],
       [ 3, 10, 16, 15, 11, 18, 16,  3, 14],
       [17,  4, 14,  2, 12, 12,  7,  8,  1],
       [ 3, 15, 17,  7,  7, 19,  3, 19, 14]])

2. Вывести на экран элемент с индексами [2, 6].

In [49]:
element_2_6 = matrix[2, 6]

element_2_6

7

3. Столбец под номером 3

In [50]:
column_3 = matrix[:, 2]

column_3

array([ 3, 16, 14, 17])

4. Каждый второй элемент третьей строки

In [51]:
every_second_element_row_3 = matrix[2, ::2]

every_second_element_row_3

array([17, 14, 12,  7,  1])

5. Элементы последнего столбца в обратном порядке

In [52]:
last_column_reversed = matrix[::-1, -1]

last_column_reversed

array([14,  1, 14,  7])

6. Изменение формы матрицы с 4x9 на 6x6 (будет ошибка, так как для изменения формы должно быть 36 элементов)

In [53]:
reshaped_matrix = np.resize(matrix, (6, 6))

reshaped_matrix

array([[ 3, 19,  3, 18,  9, 19],
       [18,  1,  7,  3, 10, 16],
       [15, 11, 18, 16,  3, 14],
       [17,  4, 14,  2, 12, 12],
       [ 7,  8,  1,  3, 15, 17],
       [ 7,  7, 19,  3, 19, 14]])

7. Возведение каждого элемента матрицы в степень 2

In [54]:
squared_matrix = np.power(matrix, 2)

squared_matrix

array([[  9, 361,   9, 324,  81, 361, 324,   1,  49],
       [  9, 100, 256, 225, 121, 324, 256,   9, 196],
       [289,  16, 196,   4, 144, 144,  49,  64,   1],
       [  9, 225, 289,  49,  49, 361,   9, 361, 196]], dtype=int32)

8. Минимум на главной диагонали

In [55]:
min_main_diagonal = np.min(np.diag(matrix))

min_main_diagonal

3

9. Максимальный элемент в предпоследнем столбце

In [56]:
max_in_penultimate_column = np.max(matrix[:, -2])

max_in_penultimate_column

19

10. Проверка, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность

In [57]:
flattened = matrix.flatten() # matrix.flatten() используется для преобразования двумерной матрицы (или многомерного массива) в одномерный массив.
is_nonincreasing = np.all(np.diff(flattened) <= 0) #Для этого вычисляется разность между соседними элементами с помощью np.diff(flattened), и затем с помощью np.all() проверяется, что все разности меньше или равны нулю. Если это так, то последовательность считается невозрастающей.

max_in_penultimate_column

19

11. Произведение ненулевых элементов на побочной диагонали

In [58]:
secondary_diagonal = np.diag(np.fliplr(matrix)) # np.fliplr(matrix) — переворачивает матрицу по горизонтали, np.diag() — извлекает элементы главной диагонали из матрицы. 
product_nonzero_secondary_diagonal = np.prod(secondary_diagonal[secondary_diagonal != 0]) # np.prod() вычисляет произведение элементов массива.

product_nonzero_secondary_diagonal

2793

12. Массив из случайных целых чисел из [-20, 20] размерностью 15

In [59]:
random_array = np.random.randint(-20, 21, 15)

random_array

array([ 19, -18, -17,  -5, -19,  10,  13,  -6, -20,   5,  -1,  13, -20,
        -4,  12])

13. Положительные элементы массива

In [60]:
positive_elements = random_array[random_array > 0]

positive_elements

array([19, 10, 13,  5, 13, 12])

14. Количество четных элементов в массиве

In [61]:
even_elements_count = np.sum(random_array % 2 == 0)

even_elements_count

7